In [17]:
import pandas as pd

df = pd.read_csv('e-comSalesData.csv')

# print(df.head())
# print(df.shape)
# df.columns
# df.describe()

# missing_summary = pd.DataFrame({
#     "Missing_Count": df.isna().sum(),
#     "Missing_Percentage": (df.isna().sum() / len(df)) * 100
# })

# missing_summary = missing_summary.sort_values(
#     "Missing_Percentage",
#     ascending=False
# )

# missing_summary
# Find the columns with missing values and sort them from highest to lowest.
# missing = df.isna().sum()
# missing.sort_values(ascending=True)

# Now display only the columns that actually have missing values, and sort them from highest to lowest.
# missing = df.isna().sum()
# missing[missing > 0].sort_values(ascending=False)

# # Find the total number of completely duplicated rows in your DataFrame.
# print(df.duplicated().sum())

# # Find the number of unique customers in your dataset.
# df["customer_id"].unique()

# df.groupby("order_status")["profit"].sum()

# Find how many orders came from each sales_channel.
# print(df.groupby("sales_channel").size())
# df["sales_channel"].value_counts()

# Find how many customers/orders belong to each customer_segment.
# print(df.groupby("customer_segment").size())
# df["customer_segment"].value_counts()

# Find the average age of customers in the dataset.
# df["customer_age"].mean()


# Find the total net_sales across all records in the dataset.
# print(df["net_sales"].sum())

# Find the total profit generated across all records.
# print(df["profit"].sum())

# Find the highest profit made on a single record/order.
# df.nlargest(1,'profit') 7083.68
# df["profit"].sort_values(ascending=False).head(1)

# Find the average profit for each sales_channel.
# print(df.groupby("sales_channel")["profit"].mean())

# Find the total net_sales for each customer_segment.
# print(df.groupby("customer_segment")["net_sales"].sum())

# Average net_sales AND average profit
# print(df.agg({"net_sales": "mean", "profit": "mean"}))
# df.groupby("sales_channel")[["net_sales", "profit"]].mean()

# For each customer_segment, calculate three things:
# Total net_sales
# Total profit
# Average profit_margin_percentage

df.groupby("customer_segment").agg({
    "net_sales": "sum",
    "profit": "sum",
    "profit_margin_percentage": "mean"
})

                    net_sales       profit  profit_margin_percentage
customer_segment
Business          17760296.90   7782525.28                 45.992864
Consumer          97201007.90  42819790.02                 46.088015
Premium           44269794.13  18177727.78                 43.224458
VIP               17903164.81   7366352.68                 43.197068

In [22]:
# For each sales_channel, find:

# Total sales (net_sales)
# Average sales (net_sales)
# Total profit (profit)
# Average profit (profit)

# print(df.groupby("sales_channel").agg({
#     "net_sales": ["sum", "mean"],
#     "profit": ["sum", "mean"]
# }))

# Using groupby() and agg(), find the total net sales and total profit for each sales_channel, 
# then determine which sales channel generated the highest total profit.
result = df.groupby("sales_channel").agg({
    "net_sales": "sum",
    "profit": "sum"
})

result.sort_values("profit", ascending=False)

                 net_sales       profit
sales_channel
Mobile App     70834782.53  30451112.22
Website        61854736.08  26639693.01
Marketplace    26696190.22  11414227.16
Social Media   17748554.91   7641363.37

In [8]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

df = pd.read_csv("e-comSalesData.csv")
X = df[["quantity","customer_age","discount_amount","shipping_cost"]]
y = df["profit"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

MAE: 301.4456821232936